//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealItem
    {
        public int Id { get; set; }
        public int MealId { get; set; }
        public int ProductId { get; set; }
        public int WeightInGrams { get; set; }
    
        public virtual Meal Meal { get; set; }
        public virtual Product Product { get; set; }
    }
}
